Import( 'env' )

envclient = env.Clone(CPPPATH=['../classes', '../h'])

envclient.VariantDir( 'build', ['.'], duplicate = 0 )

libclient = envclient.SharedLibrary( target = 'build/libClient', 
	source = [Glob('build/client.cpp')], 
	LIBPATH = '#out',
	LIBS = ['SC'])

envclient.Install( '#out', libclient )
envclient.Alias( 'install', '#out' )
