Import( 'env' )

envman = env.Clone()

#envman = VariantDir( 'build', ['.'], duplicate = 0 )

libman = envman.SharedLibrary( target = 'build/libman', 
	source = ['man.cpp'], 
	LIBPATH = '#out')

envman.Install( '#out', libman )
envman.Alias( 'install', '#out' )
