Import( 'env' )

envman = env.Clone(CPPPATH=['../classes', '../h'])

envman.VariantDir( 'build', ['.'], duplicate = 0 )

libman = envman.SharedLibrary( target = 'build/libman', 
	source = [Glob('build/man.cpp')], 
	LIBPATH = '#out', LIBS=['SC'])

envman.Install( '#out', libman )
envman.Alias( 'install', '#out' )
