Import( 'env' )

VariantDir( 'build', 'src', duplicate = 0 )

envmud = env.Clone(CXXFLAGS=['-pthread'])

libmud = envmud.SharedLibrary( target = 'build/libmud', 
	source = [Glob('build/*.cpp')], 
	LIBPATH = '#out',
	LIBS = ['SC','pthread'])

envmud.Install( '#out', libmud )
envmud.Alias( 'install', '#out' )

#craft tools
mapcreater = SConscript( dirs='mapcreater', exports = 'env' )
maploader = SConscript( dirs='maploader', exports = 'env' )
chcreater = SConscript( dirs='charcreater', exports = 'env' )
