Import( 'env' )

VariantDir( 'build', '.', duplicate = 0 )

envtalker = env.Clone(CXXFLAGS=['-pthread'])

libtalker = envtalker.SharedLibrary( target = 'build/libtalker', 
	source = [Glob('build/*.cpp')], 
	LIBPATH='#out',LIBS=['pthread','SC'])

envtalker.Install( '#out', libtalker )
envtalker.Alias( 'install', '#out' )
