Import( 'env' )

envtalker = env.Clone(CXXFLAGS=['-std=c++11', '-pthread'])

envtalker.VariantDir( 'build', ['.'], duplicate = 0 )

libtalker = envtalker.SharedLibrary( target = 'build/libtalker', 
	source = [Glob('build/talker.cpp')], 
	LIBPATH='#out',LIBS=['pthread','SC'])

envtalker.Install( '#out', libtalker )
envtalker.Alias( 'install', '#out' )
