Import( 'env' )

VariantDir( 'build', '.', duplicate = 0 )

envmaploader = env.Clone(CXXFLAGS=['-pthread'], CPPPATH=['#classes', '#h'])

libmaploader = envmaploader.SharedLibrary( target = 'build/libmaploader', 
	source = [Glob('build/*.cpp')], 
	LIBPATH = '#out',
	LIBS = ['SC','pthread'])

envmaploader.Install( '#out', libmaploader )
envmaploader.Alias( 'install', '#out' )
