Import( 'env' )

envSC = env.Clone()

#envSC = VariantDir( 'build', '.', duplicate = 0 )

SC = envSC.SharedLibrary( target = 'libSC', source = [Glob('*.cpp')] )

envSC.Install( '#out', SC )
envSC.Alias( 'install', '#out' )
