Import( 'env' )

envserver = env.Clone(CXXFLAGS=['-std=c++11', '-pthread'])

#envserver = VariantDir( 'build', ['.'], duplicate = 0 )

libserver = envserver.SharedLibrary( target = 'build/libserver', 
	source = [Glob('server.cpp')], 
	LIBPATH = '#out',
	LIBS = ['SC','pthread'])

envserver.Install( '#out', libserver )
envserver.Alias( 'install', '#out' )
