Import( 'env' )

VariantDir( 'build', '.', duplicate = 0 )

envserver = env.Clone(CXXFLAGS=['-std=c++11', '-pthread'], LINKFLAGS=['-Wall'])

libserver = envserver.SharedLibrary( target = 'build/libserver', 
	source = [Glob('build/server.cpp')], 
	LIBPATH = '#out',
	LIBS = ['SC','pthread'])

envserver.Install( '#out', libserver )
envserver.Alias( 'install', '#out' )
