Import( 'env' )

VariantDir( 'build', '.', duplicate = 0 )

envchatrm = env.Clone(CXXFLAGS=['-std=c++11', '-pthread'])

libchatrm = envchatrm.SharedLibrary( target = 'build/libchatroom', 
	source = [Glob('build/chatroom.cpp')], 
	LIBPATH = '#out',
	LIBS = ['SC','pthread'])

envchatrm.Install( '#out', libchatrm )
envchatrm.Alias( 'install', '#out' )
