Import( 'envmud' )

VariantDir( 'build', '.', duplicate = 0 )

envchcreater = envmud.Clone(CXXFLAGS=['-pthread'])

libchcreater = envchcreater.SharedLibrary( target = 'build/libchcreater', 
	source = [Glob('build/*.cpp')], 
	LIBPATH = '#out',
	LIBS = ['SC','pthread'])

envchcreater.Install( '#out', libchcreater )
envchcreater.Alias( 'install', '#out' )
