Import( 'env' )

envSystem = env.Clone(LINKFLAGS = '-ldl')

envSystem.VariantDir( 'build', ['src'], duplicate = 0 )

system = envSystem.Program(
	target = 'build/system', 
	source = ['build/system.cpp', Glob('../classes/*.cpp')],
	LIBPATH = '#out')

envSystem.Install( '#out', system )
envSystem.Alias( 'install', '#out' )
