Import( 'env','sc' )

VariantDir( 'build', '.', duplicate = 0 )

envSystem = env.Clone(CXXFLAGS='-g', LINKFLAGS = '-ldl -g', CPPPATH=['#classes', '#h'])

system = envSystem.Program(
	target = 'build/system', 
	source = ['build/system.cpp'],
	LIBPATH = '#out', LIBS=['pthread','SC'])

envSystem.Install( '#out', system )
envSystem.Alias( 'install', '#out' )
