GNUSTEP_MAKEFILES = /usr/share/GNUstep/Makefiles
  
include $(GNUSTEP_MAKEFILES)/common.make

  APP_NAME = Hello
  Hello_OBJC_FILES = Person.h Person.m test.m

  include $(GNUSTEP_MAKEFILES)/application.make
