GNUSTEP_MAKEFILES = /usr/share/GNUstep/Makefiles
SHARE_CLASS=../share

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = app
app_OBJC_FILES = test.m $(SHARE_CLASS)/person.m $(SHARE_CLASS)/webreader.m $(SHARE_CLASS)/randomwordgen.m $(SHARE_CLASS)/stem.m

include $(GNUSTEP_MAKEFILES)/tool.make

