Import( 'env' )

VariantDir( 'build', '.', duplicate = 0 )

envconui = env.Clone(CXXFLAGS=['-pthread'], CPPPATH=['../classes', '../h'])

libconui = envconui.SharedLibrary( target = 'build/libconsoleui', 
	source = [Glob('build/*.cpp')], 
	LIBPATH = '#out',
	LIBS = ['SC','pthread'])

envconui.Install( '#out', libconui )
envconui.Alias( 'install', '#out' )
